spring:
  application:
    name: discovery-client
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://server1:20001/eureka/
test:
  in: 123456789