spring:
  application:
    name: stream
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit:
        bindings:
          Test:
            consumer:
              autoBindDlq: true
              deadLetterExchange: testDLX
              deadLetterQueueName: dlq
server:
  port: 8876