spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
      #  uri: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://server1:20001/eureka/
server:
  port: 8881
